/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.arithmetics;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArithmeticsRuntimeModule extends org.eclipse.xtext.example.arithmetics.AbstractArithmeticsRuntimeModule {

}
