/*
* generated by Xtext
*/
package org.eclipse.xtext.example.arithmetics.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ArithmeticsTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
