/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.arithmetics.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ArithmeticsUiModule extends org.eclipse.xtext.example.arithmetics.ui.AbstractArithmeticsUiModule {
	public ArithmeticsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
