/*
* generated by Xtext
*/
package org.eclipse.xtext.example.arithmetics.ui.contentassist;

import org.eclipse.xtext.example.arithmetics.ui.contentassist.AbstractArithmeticsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ArithmeticsProposalProvider extends AbstractArithmeticsProposalProvider {

}
